# Generated by Django 3.2.9 on 2021-12-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211229_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='article_images',
        ),
    ]
